### PR TITLE
Added MiniResourceGrammar (Lab1) for Japanese

### PR DESCRIPTION
**Pull request by Gandhie**
Abstract files and Concrete files in a subfolder.

### CODE REVIEW

**Review by inariksit — CHANGES_REQUESTED** [review]
Can you remove the *.gfo and *.rar files from the commit? Just `git remove` them from your copy, or whatever the corresponding thing is on the GUI--don't just delete the files on your computer. Then, commit the deletions and push.

**Comment by inariksit** [comment]
Actually you can even remove them from GitHub directly: just click the file and press the trash button, like this http://www.grammaticalframework.org/~inari/remove-file-in-github.png

**Comment by Gandhie** [comment]
Think that should do it. New to Git still, so not entirely sure how everything works. Let me know if it didn't change.

**Review by inariksit — APPROVED** [review]
Looks fine now!

**Pull request merged**
